# -*- mode: python -*-
# PyInstaller spec file -- 资质代办推广助手

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('.env.example', '.'),
        ('plugins', 'plugins'),
        ('assets', 'assets'),
        ('ui/styles', 'ui/styles'),
    ],
    hiddenimports=[
        'ui.styles.theme_manager',
        'playwright.async_api',
        'playwright._impl._api_type',
        'playwright._impl._browser_type',
        'playwright._impl._connection',
        'playwright._impl._helper',
        'playwright._impl._transport',
        'apscheduler',
        'apscheduler.schedulers.background',
        'apscheduler.triggers.interval',
        'apscheduler.triggers.date',
        'bs4',
        'lxml',
        'lxml.etree',
        'fake_useragent',
        'dotenv',
        'PIL',
        'PIL.Image',
        'requests',
        'sqlite3',
        'sqlite3.dbapi2',
        'json',
        'csv',
        're',
        'asyncio',
        'threading',
        'core.ai_provider',
        'core.event_loop',
        'utils.log_handler',
        'utils.logging_setup',
        'plugins.classified',
        'plugins.classified.local_business',
        'ui.proxy_manager',
        'ui.seo_monitor',
        'ui.setup_wizard',
    ],
    hookspath=[],
    runtime_hooks=[],
    excludes=['test', 'tests', 'unittest'],
)

pyz = PYZ(a.pure, a.zipped_data)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='QualificationPromoteBot',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
